### ISSUE TITLE
User input for translation of choice

### ISSUE THREAD

**Issue by stoiandan** [stoiandan/biblegatewayquick#4]
Currently, there are several predefined translations the user can select.
A text input could be added, where the user input would override selection of predefined selection.

This also need to include validation, as to not allow malicious or wrong input

**Comment by jbust97** [comment]
I would like to work on this!

**Comment by jbust97** [comment]
Should the text input only allow one of these options : NIV, NEV, ESV, KJV, NKJV?

**Comment by stoiandan** [comment]
@jbust97 Hi! Welcome and thanks for the interest.

> Should the text input only allow one of these options : NIV, NEV, ESV, KJV, NKJV?

No, the idea would be to keep the existing `selection` element, but also below, to make a small `input ` of type text, that would treat the rest of the cases (there are other translations on Biblegateway.com supports, that are not listed here, for example `NLT`, and many others), as to not have an externally long selection list.
Basically, we will treat `NIV, NEV, ESV, KJV, NKJV` as the most popular, but then via `input` of type text, allow the user other translations as well.
Does that sound good to you as well? Thanks!

**Comment by jbust97** [comment]
Oh I see. Makes sense

**Comment by stoiandan** [comment]
Done! thank you @jbust97
